### ISSUE TITLE
一加手机会启动崩溃, 貌似是service没释放,需要在MainActivity的onDestroy()方法里面再调一下unbindService(connect)

### ISSUE THREAD

**Issue by LiifZeng** [openatx/android-uiautomator-server#15]
这个工具的想法是很赞的，如果能做到不要adb 就更赞了～

```
09-30 15:01:08.601  7047  7047 E ActivityThread: Activity com.github.uiautomator.MainActivity has leaked ServiceConnection com.github.uiautomator.MainActivity$1@9d004a8 that was originally bound here
09-30 15:01:08.601  7047  7047 E ActivityThread: android.app.ServiceConnectionLeaked: Activity com.github.uiautomator.MainActivity has leaked ServiceConnection com.github.uiautomator.MainActivity$1@9d004a8 that was originally bound here
09-30 15:01:08.601  7047  7047 E ActivityThread: 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1571)
09-30 15:01:08.601  7047  7047 E ActivityThread: 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1463)
09-30 15:01:08.601  7047  7047 E ActivityThread: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1606)
09-30 15:01:08.601  7047  7047 E ActivityThread: 	at android.app.ContextImpl.bindService(ContextImpl.java:1558)
09-30 15:01:08.601  7047  7047 E ActivityThread: 	at android.content.ContextWrapper.bindService(ContextWrapper.java:685)
09-30 15:01:08.601  7047  7047 E ActivityThread: 	at com.github.uiautomator.MainActivity.onCreate(MainActivity.java:55)
09-30 15:01:08.601  7047  7047 E ActivityThread: 	at android.app.Activity.performCreate(Activity.java:7041)
09-30 15:01:08.601  7047  7047 E ActivityThread: 	at android.app.Activity.performCreate(Activity.java:7032)
09-30 15:01:08.601  7047  7047 E ActivityThread: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1231)
09-30 15:01:08.601  7047  7047 E ActivityThread: 	at android.support.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:532)
09-30 15:01:08.601  7047  7047 E ActivityThread: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2864)
09-30 15:01:08.601  7047  7047 E ActivityThread: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2989)
09-30 15:01:08.601  7047  7047 E ActivityThread: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
09-30 15:01:08.601  7047  7047 E ActivityThread: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
09-30 15:01:08.601  7047  7047 E ActivityThread: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-30 15:01:08.601  7047  7047 E ActivityThread: 	at android.os.Looper.loop(Looper.java:164)
09-30 15:01:08.601  7047  7047 E ActivityThread: 	at android.app.ActivityThread.main(ActivityThread.java:6753)
09-30 15:01:08.601  7047  7047 E ActivityThread: 	at java.lang.reflect.Method.invoke(Native Method)
09-30 15:01:08.601  7047  7047 E ActivityThread: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
09-30 15:01:08.601  7047  7047 E ActivityThread: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
09-30 15:01:08.602  1324  9317 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@11787a5
```

**Comment by codeskyblue** [comment]
fixed
