### ISSUE TITLE
java.lang.NoSuchMethodException: android.os.Process.setArgV0(java.lang.String)

### ISSUE THREAD

**Issue by bravekingzhang** [openatx/android-uiautomator-server#5]
```java
java.lang.NoSuchMethodException: android.os.Process.setArgV0(java.lang.String)
	at java.lang.Class.getMethod(Class.java:1786)
	at com.github.uiautomator.ScreenClient.setArgV0(ScreenClient.java:37)
	at com.github.uiautomator.ScreenClient.main(ScreenClient.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
java.lang.ClassNotFoundException: android.view.SurfaceControl
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.github.uiautomator.ScreenHttpServer.initialize(ScreenHttpServer.java:49)
	at com.github.uiautomator.ScreenClient.main(ScreenClient.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```
when run ScreenClient main

**Comment by codeskyblue** [comment]
你这个有点先进啊，我还没开放出来呢。
只是放了些代码而已，有些地方没有研究透，所以没有加任何说明。

**Comment by bravekingzhang** [comment]
只是随便看哈，没想到踩到了。

**Comment by codeskyblue** [comment]
先关掉了
