### ISSUE TITLE
uiautomator.NullPointerException

### ISSUE THREAD

**Issue by codeskyblue** [openatx/android-uiautomator-server#9]
运行时抛出错误，复现方法不具体

相关代码
```java
    /**
     * Check if view exists. This methods performs a waitForExists(long) with zero timeout. This basically returns immediately whether the view represented by this UiObject exists or not.
     *
     * @param obj the ui object.
     * @return true if the view represented by this UiObject does exist
     */
    @Override
    public boolean exist(Selector obj) {
        if (obj.getChildOrSibling().length == 0 && obj.toBySelector() != null)
            return device.wait(Until.hasObject(obj.toBySelector()), 0L);
        return device.findObject(obj.toUiSelector()).exists();
    }
```

Trace内容

```
uiautomator2.JsonRpcError: -32001 Jsonrpc error: <java.lang.NullPointerException> data: java.lang.NullPointerException
	at android.support.test.uiautomator.ByMatcher.findMatches(ByMatcher.java:142)
	at android.support.test.uiautomator.ByMatcher.findMatches(ByMatcher.java:111)
	at android.support.test.uiautomator.ByMatcher.findMatch(ByMatcher.java:72)
	at android.support.test.uiautomator.UiDevice.hasObject(UiDevice.java:154)
	at android.support.test.uiautomator.Until$2.apply(Until.java:55)
	at android.support.test.uiautomator.Until$2.apply(Until.java:52)
	at android.support.test.uiautomator.WaitMixin.wait(WaitMixin.java:40)
	at android.support.test.uiautomator.WaitMixin.wait(WaitMixin.java:34)
	at android.support.test.uiautomator.UiDevice.wait(UiDevice.java:187)
	at com.github.uiautomator.stub.AutomatorServiceImpl.exist(AutomatorServiceImpl.java:744)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:467)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:352)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:283)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:251)
	at com.github.uiautomator.stub.AutomatorHttpServer.serve(AutomatorHttpServer.java:100)
	at fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:841)
```

**Comment by mingyuan-xia** [comment]
这两个不是同一个问题，getObjInfo 我修了： 3fe99c13dcefdfa6f8a19a3a9ef95de086ec699d

**Comment by codeskyblue** [comment]
看起来貌似就是这个问题

**Comment by mingyuan-xia** [comment]
这个搞还有啥问题？

**Comment by codeskyblue** [comment]
不是修复了吗？

**Comment by mingyuan-xia** [comment]
哦 你reopen我以为没搞定
